hosts:
  - name: workstation01
    ip: 192.168.1.101
    username: Administrator
    password: YourPassword123

  - name: workstation02
    ip: 192.168.1.102
    username: Administrator
    password: YourPassword123
